### ISSUE TITLE
Category listing does not make use of baseurl

### ISSUE THREAD

**Issue by GreatEmerald** [codeasashu/hcz-jekyll-blog#5]
In http://aboutashu.com/hcz-jekyll-blog/others/2016/06/04/example-content.html if you click on the "jekyll" breadcrumb, you get redirected to http://aboutashu.com/category/jekyll instead of http://aboutashu.com/hcz-jekyll-blog/category/jekyll.

Similarly, all links in http://aboutashu.com/hcz-jekyll-blog/category/jekyll don't make use of `baseurl` either.

**Comment by ashutosh2k12** [comment]
Thanks for pointing this out. This is now fixed https://github.com/ashutosh2k12/hcz-jekyll-blog/commit/9d1ebbb40ed836088c5e2dbcaa7f58774df403fa

**Comment by GreatEmerald** [comment]
Not fully fixed yet: if you look at http://aboutashu.com/hcz-jekyll-blog/category/jekyll and press "others", it still doesn't use the baseurl.

**Comment by ashutosh2k12** [comment]
Sorry, I overlooked. Just fixed again

**Comment by ashutosh2k12** [comment]
Fixed in https://github.com/ashutosh2k12/hcz-jekyll-blog/commit/7c657ee244dbed3660c3596d01a2e860a9214888

**Comment by GreatEmerald** [comment]
There is still the issue with the actual links to the posts inside the category view, though.

**Comment by GreatEmerald** [comment]
Bump. Still an issue, see for example http://aboutashu.com/hcz-jekyll-blog/category/jekyll and click on "Welcome to Jekyll!".

**Comment by GreatEmerald** [comment]
Bump. Still an issue, see for example http://aboutashu.com/hcz-jekyll-blog/category/jekyll and click on "Welcome to Jekyll!".

**Comment by GreatEmerald** [comment]
To be specific, https://github.com/ashutosh2k12/hcz-jekyll-blog/blob/gh-pages/_layouts/posts_by_category.html#L44 needs a `{{ site.url }}` too.

**Comment by brunojdo** [comment]
Hi Guys, as a matter of fact, I remove the ```/```to the 44L of posts_by_category.html and the problem with URL redirect was solved! 

```<h4 class="list-group-item-heading"><a href="{{ site.baseurl }}/{{ post.url }}">{{ post.title }}</a></h4>``` 

```<h4 class="list-group-item-heading"><a href="{{ site.baseurl }}{{ post.url }}">{{ post.title }}</a></h4>```

I going to do a PR for this.

**Comment by brunojdo** [comment]
Hi Guys, as a matter of fact, I still have a little problem with this URL redirect in categories.  When I working in the project in localhost, the redirect is point to my dns brunojdo.github.io..., instead of 127.0.0.1:4000/.... 

So, to solve this I remove the ```/``` to the 44L of posts_by_category.html and this problem with URL redirect stopped!

Old: ```<h4 class="list-group-item-heading"><a href="{{ site.baseurl }}/{{ post.url }}">{{ post.title }}</a></h4>```

```<h4 class="list-group-item-heading"><a href="{{ site.baseurl }}{{ post.url }}">{{ post.title }}</a></h4>```

I going to do a PR for this.
